In [6]:
import pandas as pd
adv_consume = pd.read_csv('D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_A.csv', encoding='utf-8')
print(adv_consume.head())

   TRAVEL_ID         ADV_NM  ADV_SEQ  PAYMENT_NUM          BRNO      STORE_NM  \
0  a_a007376         교통카드충전        0            1           NaN       CU용인마북점
1  a_a000122             잡화        4            4           NaN  지악(춘천)방향 휴게소
2  a_a003807             식품        0            3           NaN      이마트 청계천점
3  a_a009440           경량패딩        1            1  3.588500e+09       신성통상(주)
4  a_a017885  테르메덴 풀&스파 이용권        0            2           NaN          테르메덴

          ROAD_NM_ADDR            LOTNO_ADDR  ROAD_NM_CD      LOTNO_CD  \
0                  NaN                   NaN         NaN           NaN
1  강원 원주시 신림면 다리실2길 32    강원 원주시 신림면 금창리 500   4457129.0  4.213039e+09
2                  NaN                   NaN         NaN           NaN
3   제주특별자치도 제주시 신광로 29  제주특별자치도 제주시 연동 272-5   3349109.0  5.011014e+09
4                  NaN                   NaN         NaN           NaN

                PAYMENT_DT  PAYMENT_MTHD_SE  PAYMENT_AMT_WON  \
0                      NaN              3.0            10000
1  2022-08-09 12:06:00.000              1.0             6800
2                      NaN              1.0            81000
3  2022-10-28 11:27:00.000              1.0            69800
4                      NaN              4.0            39990

                PAYMENT_ETC        SGG_CD
0                    교통카드충전  4.146311e+09
1                   다솜/롤리폴리           NaN
2  고기;깻잎;떡;양파;감자;라면;사과;과자 등  1.114016e+09
3     MSD5JP1502;MSC4TU2001           NaN
4             테르메덴 풀&스파 이용권  4.150036e+09

In [1]:

# 파일 경로 리스트
file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codea_코드A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codeb_코드B.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_sgg_시군구코드.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_A.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_poi_master_POIMaster.csv",
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_A.csv",
]

In [3]:
file_paths = [
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codea_코드A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codeb_코드B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_sgg_시군구코드.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_B.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_poi_master_POIMaster.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_B.csv",
]

In [ ]:
file_paths = [
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codea_코드A.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codeb_코드B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_sgg_시군구코드.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_C.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_poi_master_POIMaster.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_C.csv",
]

In [ ]:
file_paths = [
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codea_코드A.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_codeb_코드B.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tc_sgg_시군구코드.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_D.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_poi_master_POIMaster.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_D.csv",
]

In [19]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_adv_consume_his_사전소비내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8')  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_adv_consume_his_사전소비내역.csv", index=False, encoding='utf-8')

   TRAVEL_ID         ADV_NM  ADV_SEQ  PAYMENT_NUM          BRNO      STORE_NM  \
0  a_a007376         교통카드충전        0            1           NaN       CU용인마북점
1  a_a000122             잡화        4            4           NaN  지악(춘천)방향 휴게소
2  a_a003807             식품        0            3           NaN      이마트 청계천점
3  a_a009440           경량패딩        1            1  3.588500e+09       신성통상(주)
4  a_a017885  테르메덴 풀&스파 이용권        0            2           NaN          테르메덴

          ROAD_NM_ADDR            LOTNO_ADDR  ROAD_NM_CD      LOTNO_CD  \
0                  NaN                   NaN         NaN           NaN
1  강원 원주시 신림면 다리실2길 32    강원 원주시 신림면 금창리 500   4457129.0  4.213039e+09
2                  NaN                   NaN         NaN           NaN
3   제주특별자치도 제주시 신광로 29  제주특별자치도 제주시 연동 272-5   3349109.0  5.011014e+09
4                  NaN                   NaN         NaN           NaN

                PAYMENT_DT  PAYMENT_MTHD_SE  PAYMENT_AMT_WON  \
0                      NaN              3.0            10000
1  2022-08-09 12:06:00.000              1.0             6800
2                      NaN              1.0            81000
3  2022-10-28 11:27:00.000              1.0            69800
4                      NaN              4.0            39990

                PAYMENT_ETC        SGG_CD
0                    교통카드충전  4.146311e+09
1                   다솜/롤리폴리           NaN
2  고기;깻잎;떡;양파;감자;라면;사과;과자 등  1.114016e+09
3     MSD5JP1502;MSC4TU2001           NaN
4             테르메덴 풀&스파 이용권  4.150036e+09

In [14]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_visit_area_info_방문지정보_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_visit_area_info_방문지정보.csv", index=False, encoding='utf-8')

   VISIT_AREA_ID  TRAVEL_ID  VISIT_ORDER VISIT_AREA_NM VISIT_START_YMD  \
0     2210300006  a_a015688            5        프로방스마을      2022-10-30
1     2208050001  a_a000164            1        친구/친지집      2022-08-05
2     2210030002  a_a004293            2       병점역 1호선      2022-10-03
3     2208200003  a_a000491           12         더현대서울      2022-08-20
4     2208110007  a_a000172           13        강릉중앙시장      2022-08-11

  VISIT_END_YMD        ROAD_NM_ADDR           LOTNO_ADDR     X_COORD  \
0    2022-10-30  경기 파주시 탄현면 새오리로 77  경기 파주시 탄현면 성동리 82-1  126.685239
1    2022-08-05                 NaN       경기도 안산시 단원구 와동         NaN
2    2022-10-03      경기 화성시 떡전골로 97     경기 화성시 진안동 824-1    127.0332
3    2022-08-20    서울 영등포구 여의대로 108      서울 영등포구 여의도동 22  126.928446
4    2022-08-11       강원 강릉시 금성로 21        강원 강릉시 성남동 50  128.898624

     Y_COORD  ...  POI_NM RESIDENCE_TIME_MIN VISIT_AREA_TYPE_CD REVISIT_YN  \
0  37.790405  ...     NaN               60.0                  7          Y
1        NaN  ...     NaN                NaN                 22        NaN
2  37.206753  ...     병점역               30.0                  9          Y
3  37.525872  ...     NaN              180.0                  4          N
4  37.754025  ...    신흥수산               30.0                  4          N

   VISIT_CHC_REASON_CD  LODGING_TYPE_CD DGSTFN  REVISIT_INTENTION  \
0                  9.0              NaN    4.0                4.0
1                  NaN              NaN    NaN                NaN
2                  6.0              NaN    4.0                5.0
3                  2.0              NaN    5.0                5.0
4                  1.0              NaN    4.0                4.0

   RCMDTN_INTENTION   SGG_CD
0               4.0      NaN
1               NaN  41273.0
2               5.0      NaN
3               5.0      NaN
4               4.0      NaN

[5 rows x 23 columns]

In [16]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_consume_his_활동소비내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_activity_consume_his_활동소비내역.csv", index=False, encoding='utf-8')

   TRAVEL_ID  VISIT_AREA_ID  ACTIVITY_TYPE_CD  ACTIVITY_TYPE_SEQ  \
0  a_a004739     2210020002                 3                  0
1  a_a002397     2209170002                 3                  1
2  a_a017904     2211110007                 1                  0
3  a_a018111     2211130004                 1                  0
4  a_a005012     2210120010                 1                  0

   CONSUME_HIS_SEQ  CONSUME_HIS_SNO  PAYMENT_NUM          BRNO       STORE_NM  \
0                0                1            2           NaN        아침고요수목원
1                1                0            1           NaN          에버랜드
2                0                1            2  5.918702e+09           금별맥주
3                0                1            2  3.328101e+09        주식회사필모어
4                0                1            1  6.448101e+09  박가네푸드시스템 주식회사

              ROAD_NM_ADDR               LOTNO_ADDR  ROAD_NM_CD      LOTNO_CD  \
0       경기 가평군 상면 수목원로 432      경기 가평군 상면 행현리 623-3   3216056.0  4.182033e+09
1        에버랜드로 199 삼성물산(주)                      NaN         NaN           NaN
2          서울 마포구 마포대로 110        서울 마포구 공덕동 255-16   2113001.0  1.144010e+09
3  경기 고양시 일산동구 일산로380번길 15  경기 고양시 일산동구 정발산동 1296-6   4379164.0  4.128510e+09
4           서울 종로구 종로32길 7       서울 종로구 종로5가 138-10   4100322.0  1.111016e+09

                PAYMENT_DT  PAYMENT_MTHD_SE  PAYMENT_AMT_WON  \
0  2022-10-02 00:00:00.000              1.0          22000.0
1                      NaN              4.0          33000.0
2  2022-11-11 22:32:00.000              1.0          31400.0
3  2022-11-13 14:10:00.000              1.0          48000.0
4  2022-10-12 16:26:00.000              1.0          10000.0

                   PAYMENT_ETC        SGG_CD
0                           대인           NaN
1                          NaN  4.146125e+09
2  봄베이토닉하이볼;호세쿠엘보;바지락버터술찜;파스타면           NaN
3     4.LASAGNA;7.GNOCCHI;COKE           NaN
4                          NaN           NaN

In [17]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_mvmn_consume_his_이동수단소비내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_mvmn_consume_his_이동수단소비내역.csv", index=False, encoding='utf-8')

   TRAVEL_ID  MVMN_SE PAYMENT_SE  PAYMENT_SEQ        MVMN_SE_NM  PAYMENT_NUM  \
0  a_a000279        1        주유비            0  자가용(승용/승합/트럭 등등)            3
1  a_a004250        1        주유비            0  자가용(승용/승합/트럭 등등)            2
2  a_a003984        8        교통비           11         새마을/무궁화열차            1
3  a_a000336        1        통행료            0  자가용(승용/승합/트럭 등등)            1
4  a_a014619       50        교통비            0          버스 + 지하철            1

           BRNO STORE_NM               PAYMENT_DT  PAYMENT_MTHD_SE  \
0           NaN      NaN                      NaN              NaN
1           NaN      NaN                      NaN              NaN
2  3.148210e+09   한국철도공사  2022-09-21 18:18:00.000              NaN
3           NaN      NaN                      NaN              NaN
4           NaN      NaN                      NaN              NaN

   PAYMENT_AMT_WON PAYMENT_ETC
0          70000.0         NaN
1          50000.0         NaN
2              0.0         기차표
3          11000.0         NaN
4          10000.0         NaN

In [18]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_travel_여행_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_travel_여행_D.csv", index=False, encoding='utf-8')

   TRAVEL_ID TRAVEL_NM TRAVELER_ID       TRAVEL_PURPOSE TRAVEL_START_YMD  \
0  a_a014262       A03     a014262           1;11;2;22;       2022-10-29
1  a_a006728       A03     a006728    21;24;5;22;26;27;       2022-10-10
2  a_a015745       A02     a015745               1;2;6;       2022-10-31
3  a_a010544       A03     a010544         21;22;24;26;       2022-11-01
4  a_a012058       A03     a012058  1;4;10;12;21;22;26;       2022-11-05

  TRAVEL_END_YMD MVMN_NM      TRAVEL_PERSONA       TRAVEL_MISSION  \
0     2022-10-30     자가용                 NaN           1;11;2;22;
1     2022-10-11     자가용                 NaN    21;24;5;22;26;27;
2     2022-11-03  대중교통 등                 NaN               1;2;6;
3     2022-11-02     자가용                 NaN         21;22;24;26;
4     2022-11-06  대중교통 등  수도권 외 거주 39세 이하 커플  1;4;10;12;21;22;26;

  TRAVEL_MISSION_CHECK
0               2;1;22
1               6;1;22
2              13;3;28
3              1;22;26
4              1;21;22

In [20]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_companion_info_동반자정보_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_companion_info_동반자정보_D.csv", index=False, encoding='utf-8')

   COMPANION_SEQ  TRAVEL_ID  REL_CD  COMPANION_GENDER  COMPANION_AGE_GRP  \
0              9  a_a003353      10                 1                  3
1              1  a_a007584       7                 2                  3
2              2  a_a003406       2                 2                  1
3              1  a_a004691       1                 1                  6
4              1  a_a008467       8                 2                  4

   COMPANION_SITUATION
0                    2
1                    3
2                    1
3                    1
4                    1

In [21]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_move_his_이동내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_move_his_이동내역_D.csv", index=False, encoding='utf-8')

   TRAVEL_ID     TRIP_ID  START_VISIT_AREA_ID  END_VISIT_AREA_ID START_DT_MIN  \
0  a_a001352  2208260004                  NaN       2.208260e+09          NaN
1  a_a002778  2210010004                  NaN       2.210010e+09          NaN
2  a_a018009  2211110007                  NaN       2.211110e+09          NaN
3  a_a002636  2210010004                  NaN       2.210010e+09          NaN
4  a_a006457  2210120004                  NaN       2.210120e+09          NaN

                END_DT_MIN  MVMN_CD_1  MVMN_CD_2
0  2022-08-26 12:00:00.000       15.0        NaN
1  2022-10-01 13:00:00.000       15.0        NaN
2  2022-11-11 16:30:00.000       15.0        NaN
3  2022-10-01 13:30:00.000        1.0        NaN
4  2022-10-12 15:30:00.000        1.0       15.0

In [22]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_activity_his_활동내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_activity_his_활동내역.csv", index=False, encoding='utf-8')

   TRAVEL_ID  VISIT_AREA_ID  ACTIVITY_TYPE_CD  ACTIVITY_TYPE_SEQ ACTIVITY_ETC  \
0  a_a001132     2209030003                 2                  0          NaN
1  a_a002873     2209280003                 4                  0          NaN
2  a_a004395     2210020002                 5                  1          NaN
3  a_a005221     2210010002                 1                  1          NaN
4  a_a000508     2208280001                 7                  0          NaN

  ACTIVITY_DTL RSVT_YN EXPND_SE ADMISSION_SE
0           향수       N        5          NaN
1          NaN     NaN      NaN          NaN
2          NaN     NaN      NaN          NaN
3     복숭아 아이스티       N        2          NaN
4          NaN     NaN      NaN          NaN

In [23]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_traveller_master_여행객 Master_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_traveller_master_여행객 Master.csv", index=False, encoding='utf-8')

  TRAVELER_ID  RESIDENCE_SGG_CD GENDER  AGE_GRP  EDU_NM  EDU_FNSH_SE  \
0     b015583                41      여       20       6          1.0
1     a001105                30      남       30       6          1.0
2     a001673                41      여       30       4          1.0
3     a017690                41      여       30       6          1.0
4     c006666                28      여       30       6          1.0

   MARR_STTS  FAMILY_MEMB  JOB_NM  JOB_ETC  ...  TRAVEL_STYL_7  TRAVEL_STYL_8  \
0        1.0            5     3.0      NaN  ...              1              7
1        1.0            2     3.0      NaN  ...              6              5
2        2.0            3     NaN      1.0  ...              2              7
3        1.0            3     3.0      NaN  ...              4              5
4        1.0            3    13.0      NaN  ...              5              5

   TRAVEL_STATUS_RESIDENCE  TRAVEL_STATUS_DESTINATION  \
0                      경기도                         충남
1                    대전광역시                         경기
2                      경기도                         서울
3                      경기도                         서울
4                    인천광역시                         경기

   TRAVEL_STATUS_ACCOMPANY      TRAVEL_STATUS_YMD  TRAVEL_MOTIVE_1  \
0              2인 여행(가족 외)  2022-10-29~2022-10-30              1.0
1           3인 이상 여행(가족 외)  2022-09-03~2022-09-04              3.0
2                 자녀 동반 여행  2022-09-18~2022-09-19             10.0
3           3인 이상 여행(가족 외)  2022-11-12~2022-11-12              3.0
4                   나홀로 여행  2022-10-18~2022-10-18              1.0

   TRAVEL_MOTIVE_2  TRAVEL_MOTIVE_3  TRAVEL_COMPANIONS_NUM
0              NaN              NaN                      1
1              NaN              NaN                      7
2              7.0              1.0                      2
3              1.0              2.0                      3
4              7.0              2.0                      0

[5 rows x 36 columns]

In [24]:
import pandas as pd

file_paths = [
    "D:/국내여행로그데이터/277.국내_여행로그_데이터(수도권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_A.csv",
    "D:/국내여행로그데이터/278.국내_여행로그_데이터(동부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_B.csv",
    "D:/국내여행로그데이터/279.국내_여행로그_데이터(서부권)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_C.csv",
    "D:/국내여행로그데이터/280.국내_여행로그_데이터(제주도_및_도서지역)/01-1.정식개방데이터/Training/02.라벨링데이터/TL_csv/tn_lodge_consume_his_숙박소비내역_D.csv"
]

# 모든 데이터프레임을 리스트에 저장
dfs = []
for path in file_paths:
    try:
        df = pd.read_csv(path, encoding='utf-8',low_memory=False)  
        dfs.append(df)
    except Exception as e:
        print(f"파일 {path}를 읽는 중 오류 발생: {e}")

# 데이터프레임 결합 (Travel_ID 기준으로)
merged_df = pd.concat(dfs, axis=0, ignore_index=True)

# 결합된 데이터 확인
print(merged_df.head())

# CSV로 저장 (필요 시)
merged_df.to_csv("./combined_tn_lodge_consume_his_숙박소비내역.csv", index=False, encoding='utf-8')

   TRAVEL_ID      LODGING_NM  LODGING_PAYMENT_SEQ  LODGING_TYPE_CD RSVT_YN  \
0  a_a000290         솔잎향캠핑파크                    1                5       Y
1  a_a000805           고구마모텔                    1                2       Y
2  a_a012504            공군호텔                    1                1       Y
3  a_a001356  호텔스카이파크 센트럴명동점                    1                1       Y
4  a_a003139           스테이카키                    1                7       Y

             CHK_IN_DT_MIN           CHK_OUT_DT_MIN  PAYMENT_NUM  \
0  2022-08-24 00:00:00.000  2022-08-25 00:00:00.000            4
1  2022-09-04 00:00:00.000  2022-09-06 00:00:00.000            1
2  2022-11-03 00:00:00.000  2022-11-04 00:00:00.000            1
3  2022-08-27 00:00:00.000  2022-08-28 00:00:00.000            1
4  2022-09-24 00:00:00.000  2022-09-25 00:00:00.000            4

           BRNO      STORE_NM         ROAD_NM_ADDR          LOTNO_ADDR  \
0           NaN       솔잎향캠핑파크  경기 시흥시 수인로2107번길 52    경기 시흥시 조남동 583-2
1  1.753401e+09         호텔고구마      서울 마포구 백범로4길 16  서울 마포구 노고산동 106-77
2  1.188300e+09       공군항공안전단    서울 영등포구 여의대방로 259    서울 영등포구 신길동 1196
3           NaN  T-STAY센트럴명동점                  NaN                 NaN
4           NaN         스테이카키  서울 용산구 이태원로36길 19-8   서울 용산구 한남동 686-11

   ROAD_NM_CD      LOTNO_CD               PAYMENT_DT  PAYMENT_MTHD_SE  \
0   4397339.0  4.139012e+09                      NaN              1.0
1   4139251.0  1.144011e+09  2022-09-04 20:07:00.000              1.0
2   3118028.0  1.156013e+09  2022-11-03 16:39:00.000              1.0
3         NaN           NaN  2022-08-06 00:00:00.000              1.0
4   4106314.0  1.117013e+09  2022-07-11 05:23:00.000              1.0

   PAYMENT_AMT_WON                PAYMENT_ETC
0           160000                     글램핑(1)
1           100000                        NaN
2            36000                        NaN
3           102460  센트럴명동점 스탠다드더블객실1박+미니바무료이용
4           340000                   1F/성인 4명